version: '3'
services:
########################
# Setup Server Container
########################
  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    command: yarn start
########################
# Setup Client Container
########################
  client:
    build: ./client
    expose:
      - ${REACT_APP_PORT}
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    links:
      - server
    command: npm start