# base image
FROM node:10.16.0-alpine

# set working directory
WORKDIR /app/server

# add `/app/server/node_modules/.bin` to $PATH
ENV PATH /app/server/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/server/package.json
RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
        sqlite \
    && yarn \
    && apk del .gyp \
    && yarn add sqlite3 \
    && yarn add nodemon

# start app
CMD ["yarn", "start"]